config/routes.rb
require 'sidekiq/web'
# TODO - need to migrate Sidekiq
#Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

Cas::Engine.routes.draw do
  if Shrine.respond_to?(:presign_endpoint)
    mount Shrine.presign_endpoint(:cache) => "/files/cache/presign"
  else
    Rails.logger.info "Shrine's presign endpoint is disabled"
  end

  # TODO - fix
  # mount Shrine.upload_endpoint(:cache) => "/files/upload"

  authenticate :user, ->(u){ u.roles.include?('admin') } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users,
    class_name: "Cas::User",
    module: :devise,
    controllers: { sessions: "cas/devise/sessions" },
    skip: :registrations

  resources :activities, only: [:index]
  resources :sites, only: [:index] do
    resources :users, controller: 'sites/users'

    resources :sections, only: [:index], controller: 'sites/sections' do
      resources :contents, controller: 'sites/sections/contents'
      resources :categories, controller: 'sites/sections/categories'
    end
  end

  # used by tinymce editor
  resources :file_uploads, only: :create
  namespace :api, module: "api" do
    resources :files, only: [:create, :destroy]
  end

  root 'sites/sections#index'
end

app/models/cas/content.rb
module Cas
  class Content < ApplicationRecord

    include CasContentConcern if defined?(CasContentConcern)

    include ::PgSearch::Model
    extend ::FriendlyId

    friendly_id :title, use: :slugged
    acts_as_taggable

    serialize :metadata

    belongs_to :section
    belongs_to :category, optional: true
    belongs_to :author, class_name: "::Cas::User", optional: true

    has_many :images,
      ->{ where(media_type: :image).order("cas_media_files.order ASC") },
      class_name: "::Cas::MediaFile", as: :attachable, dependent: :destroy
    has_many :attachments,
      ->{ where(media_type: :attachment).order("cas_media_files.order ASC") },
      class_name: "::Cas::MediaFile", as: :attachable, dependent: :destroy
    has_many :activities, as: :subject

    has_many :content_to_content, foreign_key: :cas_content_id, class_name: "Cas::ContentToContent"
    has_many :related_contents, through: :content_to_content

    has_one :site, through: :section
    has_one :cover_image,
      ->{ where(media_type: :image, cover: true) },
      class_name: "::Cas::MediaFile", as: :attachable

    validates :title, presence: true

    before_validation :set_published_at
    before_save :cache_tags

    scope :published, ->{ where(published: true) }

    pg_search_scope :search, ->(query) do
      {
        query: query,
        against: [:title, :text, :location, :tags_cache],
        order_within_rank: "cas_contents.published_at DESC"
      }
    end

    def date_year
      date.year
    end

    def metadata
      if self[:metadata].is_a?(String)
        JSON.parse(self[:metadata])
      else
        super
      end
    end

    private

    def set_published_at
      if published_at.blank? && published
        self.published_at = Time.now
      end
    end

    # so we can fulltext search appropriatelly with pg_search
    def cache_tags
      category_name = "#{category.name if category.present?}"
      self.tags_cache = (tag_list + category_name).flatten.join(", ")
    end
  end
end

app/models/cas/section.rb
module Cas
  class Section < ApplicationRecord
    extend ::FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :site
    has_many :contents, dependent: :destroy
    has_many :categories, dependent: :destroy
  end
end

app/controllers/cas/sections/application_controller.rb
module Cas
  class Sections::ApplicationController < ApplicationController
    before_action :load_section

    private

    def load_section
      @section ||= ::Cas::Section.friendly.find(params[:section_id])
    end

    def scope_content_by_role(model_relation = ::Cas::Content)
      # Only admins and editors can see other people's content
      if !current_user.admin? && !current_user.editor?
        model_relation = model_relation.where(author_id: current_user.id)
      end
      model_relation
    end

    def load_categories
      @categories ||= @section.categories
    end
  end
end

app/controllers/cas/sections/categories_controller.rb
require_dependency "cas/application_controller"

module Cas
  class Sections::CategoriesController < Sections::ApplicationController
    before_action :set_category, only: [:edit, :update, :destroy]

    def index
      @categories = @section.categories
    end

    def new
      @category = ::Cas::Category.new
    end

    def edit
    end

    def create
      @category = ::Cas::Category.new(category_params)
      @category.section = @section

      if @category.save
        redirect_to section_categories_url(@section), notice: 'Categoria salva com sucesso.'
      else
        render :new
      end
    end

    def update
      if @category.update(category_params)
        redirect_to section_categories_url(@section), notice: 'Categoria salva com sucesso.'
      else
        render :edit
      end
    end

    private

    def set_category
      @category = ::Cas::Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/cas/sections/contents_controller.rb
require_dependency "cas/application_controller"

module Cas
  class Sections::ContentsController < Sections::ApplicationController
    class FileBelongsToAnotherAttachable < StandardError; end
    before_action :set_content_type

    def index
      @contents = scope_content_by_role(@section.contents)
      @contents = @contents.order('created_at desc').page(params[:page]).per(25)
    end

    def new
      @content = ::Cas::Content.new
      load_categories
    end

    def create
      @content = ::Cas::Content.new(content_params)

      success = nil
      begin
        ActiveRecord::Base.transaction do
          @content.author_id = current_user.id
          @content.section_id = @section.id
          @content.tag_list = content_params[:tag_list] if content_params[:tag_list]
          success = @content.save!
          associate_files(@content, :images)
          associate_files(@content, :attachments)
        end
      rescue ActiveRecord::RecordInvalid
        success = nil
      end

      if success
        redirect_to section_contents_url(@section), notice: 'Noticia salva com sucesso.'
      else
        load_categories
        render :new
      end
    end

    def edit
      @content = scope_content_by_role.friendly.find(params[:id])

      if @content.created_at.present? && @content.date.blank?
        @default_date = @content.created_at
      else
        @default_date = @content.date
      end

      load_categories
    end

    def update
      @content = scope_content_by_role.friendly.find(params[:id])

      success = nil
      begin
        ActiveRecord::Base.transaction do
          @content.tag_list = content_params[:tag_list]
          success = @content.update!(content_params)
          associate_files(@content, :images)
          associate_files(@content, :attachments)
        end
      rescue ActiveRecord::RecordInvalid
        success = nil
      end

      if success
        redirect_to section_contents_path
      else
        load_categories
        render :edit
      end
    end

    def destroy
      @content = scope_content_by_role.friendly.find(params[:id])
      @content.destroy

      redirect_to section_contents_path
    end

    private

    def set_content_type
      @content_type = @section.section_type
    end

    def content_params
      @content_params ||= begin
        result = params.require(:content).permit(
          :category_id,
          :title,
          :location,
          :summary,
          :published,
          :date,
          :text,
          :url,
          :embedded,
          :tag_list
        )

        unless result.keys.map(&:to_sym).include?(:published)
          result[:published] = true
        end

        if params.dig(:content, :metadata).present?
          # TODO the survey is sending empty questions and these
          # are being saved anyway. We need to filter these.
          result[:metadata] = params.dig(:content, :metadata).to_unsafe_h
        end

        result
      end
    end

    # form_key_name could be :images or :attachments
    def associate_files(item, form_key_name)
      return if params[form_key_name].blank?

      ActiveRecord::Base.transaction do
        params[form_key_name][:files].to_unsafe_h.each do |key, value|
          next if value["id"].blank?
          begin
            new_order = key.to_i + 1
            is_cover = params[form_key_name][:cover_id] == value["id"]
            image = ::Cas::MediaFile.find(value["id"])
            if image.attachable.blank?
              image.update!(cover: is_cover, order: new_order, attachable: item)
            elsif image.order.to_i != new_order || image.cover != is_cover
              image.update!(cover: is_cover, order: new_order)
            elsif image.attachable != item
              raise FileBelongsToAnotherAttachable, "File already belongs to #{item.attachable.id}"
            end
          rescue ActiveRecord::RecordNotFound
          end
        end
      end
    end
  end
end

app/controllers/cas/sites/sections/application_controller.rb
module Cas
  class Sites::Sections::ApplicationController < Sites::ApplicationController
    before_action :load_section

    private

    def load_section
      @section ||= @site.sections.friendly.find(params[:section_id])
    end

    def scope_content_by_role(model_relation = ::Cas::Content)
      # Only admins and editors can see other people's content
      if !current_user.admin? && !current_user.editor?
        model_relation = model_relation.where(author_id: current_user.id)
      end

      model_relation
    end

    def load_categories
      @categories ||= @section.categories
    end
  end
end

app/controllers/cas/sites/sections/categories_controller.rb
require_dependency "cas/application_controller"

module Cas
  class Sites::Sections::CategoriesController < Sites::Sections::ApplicationController
    before_action :set_category, only: [:edit, :update, :destroy]

    def index
      @categories = @section.categories
    end

    def new
      @category = ::Cas::Category.new
    end

    def edit
    end

    def create
      @category = ::Cas::Category.new(category_params)
      @category.section = @section

      if @category.save
        redirect_to site_section_categories_url(@site, @section), notice: 'Categoria salva com sucesso.'
      else
        render :new
      end
    end

    def update
      if @category.update(category_params)
        redirect_to site_section_categories_url(@site, @section), notice: 'Categoria salva com sucesso.'
      else
        render :edit
      end
    end

    private

    def set_category
      @category = ::Cas::Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/cas/sites/sections/contents_controller.rb
require_dependency "cas/application_controller"

module Cas
  class Sites::Sections::ContentsController < Sites::Sections::ApplicationController
    class FileBelongsToAnotherAttachable < StandardError; end
    before_action :set_content_type

    def index
      @contents = scope_content_by_role(@section.contents)
      @contents = @contents.order('created_at desc').page(params[:page]).per(25)
    end

    def new
      @content = ::Cas::Content.new
      @content.content_to_content.build
      load_categories
    end

    def create
      @content = ::Cas::Content.new(content_params)
      @content.author_id = current_user.id
      @content.section_id = @section.id

      success = nil
      begin
        ActiveRecord::Base.transaction do
          success = serialize_form_value_into_models
        end
      rescue ActiveRecord::RecordInvalid
        Rails.logger.info "Errors: #{@content.errors.full_messages.inspect}"
        success = nil
      end

      if success
        redirect_to site_section_contents_url(@site, @section), notice: 'Noticia salva com sucesso.'
      else
        load_categories
        render :new
      end
    end

    def edit
      @content = scope_content_by_role.friendly.find(params[:id])

      if @content.created_at.present? && @content.date.blank?
        @default_date = @content.created_at
      else
        @default_date = @content.date
      end

      load_categories
    end

    def update
      @content = scope_content_by_role.friendly.find(params[:id])

      success = nil
      begin
        ActiveRecord::Base.transaction do
          success = serialize_form_value_into_models
        end
      rescue ActiveRecord::RecordInvalid => e
        Rails.logger.info "Content Invalid: #{e.message} - #{@content.errors.inspect}"
        success = nil
      end

      if success
        redirect_to site_section_contents_url(@site, @section)
      else
        load_categories
        render :edit
      end
    end

    def destroy
      @content = scope_content_by_role.friendly.find(params[:id])
      @content.destroy

      redirect_to site_section_contents_url(@site, @section)
    end

    private

    def set_content_type
      @content_type = @section.section_type
    end

    def content_params
      @content_params ||= begin
        # When no file is uploaded, when the content form is submitted the
        # `file` input ends up being sent empty (e.g file: [""]). This confuses
        # Rails.
        if params[:content][:file].present?
          params[:content].delete(:file) if params[:content][:file].map(&:presence)&.compact.blank?
        end

        result = params.require(:content).permit(
          :category_id,
          :title,
          :location,
          :summary,
          :published,
          :date,
          :text,
          :url,
          :embedded,
          :tag_list,
          :file,
          :content_to_content
        )

        if result[:content_to_content].present?
          result[:content_to_content] = result[:content_to_content].split(",").map { |id|
            # Params comes like this:
            #
            # {
            #   content_to_content: "f0ba2d53-07ba-4e66-be76-edbcfc2559a5,7719b57e-fc23-45dc-8a42-faec74806b80"
            # }
            Cas::ContentToContent.new(cas_other_content_id: id)
          }
        else
          result[:content_to_content] = []
        end

        unless result.keys.map(&:to_sym).include?(:published)
          result[:published] = true
        end

        if params.dig(:content, :metadata).present?
          # TODO the survey is sending empty questions and these
          # are being saved anyway. We need to filter these.
          result[:metadata] = params.dig(:content, :metadata).to_unsafe_h
        end

        result
      end
    end

    # This is called by create and update methods and do basically the same
    # thing except for one being a `save!` and the other being an `update!`
    def serialize_form_value_into_models
      event = @content.new_record? ? :create : :update

      @content.tag_list = content_params[:tag_list] if content_params[:tag_list]
      associate_related_content(@content)
      Rails.logger.info "Errors: #{@content.errors.inspect}"

      success = if event == :create
                  @content.save!
                else
                  @content.update!(content_params)
                end

      associate_files(@content, :images)
      associate_files(@content, :attachments)

      ::Cas::Activity.create!(
        user: current_user,
        site: @site,
        subject: @content,
        event_name: event
      )

      success
    end

    # This takes what we got in params's `content_to_content` and assigns in
    # @content.
    def associate_related_content(content)
      return if params.dig(:content, :content_to_content).blank?

      content.content_to_content = []
      content_params[:content_to_content]&.each do |content_to_content|
        content.content_to_content << content_to_content
      end
    end

    # form_key_name could be :images or :attachments
    def associate_files(item, form_key_name)
      return if params[form_key_name].blank?

      ActiveRecord::Base.transaction do
        params[form_key_name][:files].to_unsafe_h.each do |key, value|
          next if value["id"].blank?
          begin
            new_order = key.to_i + 1
            is_cover = params[form_key_name][:cover_id] == value["id"]
            image = ::Cas::MediaFile.find(value["id"])
            if image.attachable.blank?
              image.update!(cover: is_cover, order: new_order, attachable: item)
            elsif image.order.to_i != new_order || image.cover != is_cover
              image.update!(cover: is_cover, order: new_order)
            elsif image.attachable != item
              raise FileBelongsToAnotherAttachable, "File already belongs to #{item.attachable.id}"
            end
          rescue ActiveRecord::RecordNotFound
          end
        end
      end
    end
  end
end

app/controllers/cas/sites/sections_controller.rb
module Cas
  class Sites::SectionsController < Sites::ApplicationController
    def index
      @sections = @site.sections.all
    end
  end
end

app/views/cas/sections/contents/_form.html.erb
<%= simple_form_for ([@section, @content]) do |f| %>
  <% if display_field?(:category) %>
    <p>
      <%= f.input :category_id,
        label: "Categoria:",
        collection: @categories.map { |c| [c.name, c.id] },
        input_html: { class: 'js-select2' }
      %>
    </p>
  <% end %>

  <% if display_field?(:title) %>
    <p>
      <%= f.input :title, as: :string, label: 'Título:' %>
    </p>
  <% end %>

  <% if display_field?(:summary) %>
    <p>
      <%= f.input :summary, as: :text, label: 'Resumo' %>
    </p>
  <% end %>

  <% if display_field?(:location) %>
    <p>
      <%= f.input :location, as: :string, label: 'Local:' %>
    </p>
  <% end %>

  <% if display_field?(:date) %>
    <% field = field_properties(:date) %>
    <p>
      <%= f.input :date,
        as: (field.format.map(&:to_s).include?("hour") ? :datetime : :date),
        label: 'Data:',
        order: field.format,
        default: @default_date
      %>
    </p>
  <% end %>

  <% if display_field?(:tags) %>
    <% autocomplete = ActsAsTaggableOn::Tag.all.map { |t| {value: t.name, text: t.name} } %>
    <%= f.input :tag_list,
      as: :string,
      required: false,
      label: "Tags",
      input_html: {
        value: f.object.tag_list.join(", "),
        class: "js-tags",
        data: { autocomplete: autocomplete.to_json }
      }
    %>
  <% end %>

  <% if display_field?(:url) %>
    <p>
      <%= f.input :url, label: 'URL:' %>
    </p>
  <% end %>

  <% if display_field?(:text) %>
    <p>
      <%= f.input :text, as: :text, label: 'Texto', input_html: { class: 'editor' } %>
    </p>
  <% end %>

  <% if display_field?(:embedded) %>
    <p>
      <%= f.input :embedded, label: 'URL:' %>
    </p>
  <% end %>

  <% if display_field?(:attachments) %>
    <%= render 'form_attachments', f: f %>
  <% end %>

  <% if display_field?(:images) %>
    <%= render 'form_images', f: f %>
  <% end %>

  <div class="actions">
    <%= f.submit "Salvar", id: 'submit' %>
  </div>
<% end %>

app/views/cas/sections/contents/_form_for_content.html.erb
<%= simple_form_for ([@section, @content]) do |f| %>
  <% if display_field?(:category) %>
    <p>
      <%= f.input :category_id,
        label: "Categoria:",
        collection: @categories.map { |c| [c.name, c.id] },
        input_html: { class: 'js-select2' }
      %>
    </p>
  <% end %>

  <% if display_field?(:title) %>
    <p>
      <%= f.input :title, required: true, as: :string, label: 'Título:' %>
    </p>
  <% end %>

  <% if display_field?(:summary) %>
    <p>
      <%= f.input :summary, as: :text, label: 'Resumo' %>
    </p>
  <% end %>

  <% if display_field?(:location) %>
    <p>
      <%= f.input :location, as: :string, label: 'Local:' %>
    </p>
  <% end %>

  <% if display_field?(:date) %>
    <% field = field_properties(:date) %>
    <p>
      <%= f.input :date,
        as: (field.format.map(&:to_s).include?("hour") ? :datetime : :date),
        label: 'Data:',
        order: field.format,
        default: @default_date
      %>
    </p>
  <% end %>

  <% if display_field?(:tags) %>
    <% autocomplete = ActsAsTaggableOn::Tag.all.map { |t| {value: t.name, text: t.name} } %>
    <%= f.input :tag_list,
      as: :string,
      required: false,
      label: "Tags",
      input_html: {
        value: f.object.tag_list.join(", "),
        class: "js-tags",
        data: { autocomplete: autocomplete.to_json }
      }
    %>
  <% end %>

  <% if display_field?(:url) %>
    <p>
      <%= f.input :url, label: 'URL:' %>
    </p>
  <% end %>

  <% if display_field?(:text) %>
    <p>
      <%= f.input :text, as: :text, label: 'Texto', input_html: { class: 'editor' } %>
    </p>
  <% end %>

  <% if display_field?(:embedded) %>
    <p>
      <%= f.input :embedded, label: 'URL:' %>
    </p>
  <% end %>

  <% if display_field?(:attachments) %>
    <%= render 'form_attachments', f: f %>
  <% end %>

  <% if display_field?(:images) %>
    <%= render 'form_images', f: f %>
  <% end %>

  <div class="actions">
    <%= f.submit "Salvar", id: 'submit' %>
  </div>
<% end %>

app/views/cas/sections/contents/edit.html.erb
<p><%= @section.name %></p>
<h1>Editar: <%= @content.title %></h1>

<%= render "form_for_#{@content_type}" %>

<%= link_to 'Voltar', section_contents_path %>

app/views/cas/sections/contents/index.html.erb
<div class="grid">
  <div class="col-1-2">
    <h1><%= @section.name %></h1>
  </div>
  <div class="col-1-2 section-options">
    <% if Cas::SectionConfig.new(@section).form_has_field?(:category) %>
      <%= link_to "Categorias", section_categories_path(@section), id: 'manage-categories' %>
    <% end %>
  </div>
</div>

<%= link_to 'Novo conteúdo',
  new_section_content_path(@section.id),
  id: 'new-content' %>

<br />
<br />

<table>
  <thead>
    <tr>
      <th colspan="<%= Cas::SectionConfig.new(@section).list_fields.count %>">Título</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @contents.each do |content| %>
    <tr id="content-<%= content.id %>">
      <% column_no = 1 %>

      <% Cas::SectionConfig.new(@section).list_fields.each do |field| %>
        <td>
          <% if field == 'created_at' %>
            <% value = l(content.created_at, format: :short) %>
          <% elsif field == 'date_year' %>
            <% value = content.date.year %>
          <% elsif field == 'date' %>
            <% value = content.date.strftime("%d/%m/%Y") %>
          <% elsif field == 'date_time' %>
            <% if content.date.present? %>
              <% value = l(content.date, format: :short) %>
            <% end %>
          <% else %>
            <% value = content.public_send(field) %>
          <% end %>

          <% if column_no == 1 %>
            <%= link_to value,
              edit_section_content_path(@section.id, content),
              id: "edit-content-#{content.id}" %>
          <% else %>
            <%= value %>
          <% end %>

          <% column_no += 1 %>
        </td>
      <% end %>
      <td>
        <%= link_to 'Excluir', section_content_path(@section.id, content),
          method: :delete,
          data: { confirm: 'Tem certeza?' },
          id: "delete-content-#{content.id}" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>

<%= paginate @contents %>

app/views/cas/sections/contents/new.html.erb
<h1><%= @section.name %>: criar</h1>

<%= render "form_for_#{@content_type}" %>

<%= link_to 'Voltar', section_contents_path %>